version: '3.4'

services:
  productdb:
    image: mongo

  webapplication4:
    image: ${DOCKER_REGISTRY-}webapplication4
    build:
      context: .
      dockerfile: WebApplication4/Dockerfile

volumes:
  mongo_data: