version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  webapplication4:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatebaseSettings:ConnectionString=mongodb://productdb:27017"
    depends_on:
     - productdb
    ports:
      - "8000:80"
